# You've seen properties as things link hibernate.connection.url
# server.port=
# server.servlet.context-path=
server:
  port: 9005
  servlet:
    context-path: /
# in a properties file, it would look like spring.application.name
spring:
  application:
    name: frittte
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=frittte
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

# Default actuator gives us the health endpoint, we will add a few others
management:
  endpoints:
    web:
      exposure:
        includes:
          - "beans"
          - "health"
          - "info"
